### ISSUE TITLE
Update http-mock to work with jeremeamia/SuperClosure v2

### ISSUE THREAD

**Issue by fizzka** [InterNations/http-mock#12]
dependent lib jeremeamia/SuperClosure was updated to v2, and your code stopped to work(

PHP Fatal error:  Class 'Jeremeamia\SuperClosure\SerializableClosure' not found in /work/www/tsw/vendor/internations/http-mock/src/InterNations/Component/HttpMock/Matcher/AbstractMatcher.php on line 32

**Comment by acobster** [comment]
Forked and working on this. PR coming soon.

**Comment by acobster** [comment]
Hmmm...was this addressed in https://github.com/InterNations/http-mock/commit/203f6ef1277ed61571e4026134261ea5db5c619e ?

**Comment by lstrojny** [comment]
Yep, 203f6ef1277ed61571e4026134261ea5db5c619e should resolve it.

**Comment by oschwald** [comment]
This hit me too. It'd be nice to do a release with this fix.
