### ISSUE TITLE
Make new release with latest code updates

### ISSUE THREAD

**Issue by toothfairy** [InterNations/http-mock#16]
Jeremeamia\SuperClosure namespace compatibility was fixes here https://github.com/InterNations/http-mock/commit/203f6ef1277ed61571e4026134261ea5db5c619e, but the latest release doesn't contain that changes, thus master branch has to be used which is not super cool. It would be really great to have some latest stable version released. Thanks!

**Comment by bencoder** [comment]
:+1: This would be great

**Comment by lstrojny** [comment]
Fixed and released!

**Comment by toothfairy** [comment]
Great! :+1:
