### ISSUE TITLE
Save and return post data.

### ISSUE THREAD

**Issue by cosmorogers** [InterNations/http-mock#18]
Hi

It would be useful for me if data posted to the mocked server was saved and returned when using in tests. You could then check the post data was as expected, eg

    $this->assertSame( 'expected', $this->http->requests->latest()->getPostField( 'my_field' ) );

I have implemented this quickly in my fork, https://github.com/cosmorogers/http-mock, shall I make a pull request for this?

**Comment by lstrojny** [comment]
Sorry for the late response, I was on a long vacation. I very much like the idea, it makes a lot of sense. Will this work for PUT data as well?

**Comment by lstrojny** [comment]
Pushed in 14171ab08197cd6f593edbb8d2355e897aef01cc
