### ISSUE TITLE
Multiple servers in test case

### ISSUE THREAD

**Issue by AlexMarlo** [InterNations/http-mock#21]
In some test i need to have not just one but several http-mock servers

**Comment by lstrojny** [comment]
Can you try out https://github.com/InterNations/http-mock/tree/feature/facade-map and see if it does what you want?

**Comment by AlexMarlo** [comment]
yeah, that is better, but i add some changes

In **HttpMockTrait** i've changed function **setUpHttpMockBeforeClass** to

```
    protected static function setUpHttpMockBeforeClass($port = null, $host = null, $basePath = null, $name = null)
    {
        $port = $port ?: 28080;
        $host = $host ?: 'localhost';

        $facade = new HttpMockFacade($port, $host, $basePath);
        if ($name === null) {
            static::$staticHttp = $facade;
        } elseif( static::$staticHttp instanceof HttpMockFacadeMap) {
            static::$staticHttp->offsetSet( $name, $facade);
        } else {
            static::$staticHttp = new HttpMockFacadeMap([$name => $facade]);
        }

        ServerManager::getInstance()->add($facade->server);
    }
```
and in **HttpMockFacadeMap** function **offsetSet** to 

```
    public function offsetSet($offset, $value)
    {
      $this->facadeMap[$offset] = $value;
    }
```
All this to support adding multiple servers.
You can put this in you code and commit and merge to master or i can make pull-request?

**Comment by lstrojny** [comment]
Fixed it in the branch.

**Comment by AlexMarlo** [comment]
Great, when it is going to be merged to master?

**Comment by lstrojny** [comment]
Now 😄

**Comment by AlexMarlo** [comment]
Great. Thanks.
