### ISSUE TITLE
Check that server didn't receive any or particular request

### ISSUE THREAD

**Issue by AlexMarlo** [InterNations/http-mock#23]
I have functionality when i need to know that part of the code which call remote server wasn't called.
For now i don't see such functionality in library.
Any ideas?

**Comment by lstrojny** [comment]
Can’t you check that requests are empty?

**Comment by AlexMarlo** [comment]
I don't see in RequestCollectionFacade public function to get request list.

**Comment by lstrojny** [comment]
True, let’s think about an API. What about saying `$this->assertCount(2, $this->http->requests);`?

**Comment by lstrojny** [comment]
PR is #24

**Comment by AlexMarlo** [comment]
great, but what about the case when i want to now that particular request wasn't received?

**Comment by lstrojny** [comment]
You can do something like this: `$this->assertNotSame('/unexpected', $this->http->request->latest()->getRequestUri());`

Alternatively we would need to match against all requests and say "assert that there hasn’t been a request matching the following criteria". But I am not sure that’s needed.

**Comment by alexeyshockov** [comment]
I think that the last part of this issue is similar to #25. With real mocks this checks will be created automatically (how many times particular request should be done).

**Comment by lstrojny** [comment]
Closing this for now, ok?
