### ISSUE TITLE
Real mocks instead of stubs

### ISSUE THREAD

**Issue by alexeyshockov** [InterNations/http-mock#25]
I think that now HTTP mocks are more simple stubs, they aren't mocks in classical meaning (because they don't set any assertions based on prepared HTTP queries).

For example, if I write a test with a classic mock object in PHPUnit:

``` php
    public function testMock()
    {
        $mock = $this->getMock(\ArrayObject::class);
        $mock->expects($this->once())->method('count')->willReturn(5);

        assertTrue(true);
    }
```

I will get it failed:

```
There was 1 failure:

1) ExampleTest::testMock
Expectation failed for method name is equal to <string:count> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
```

But with HTTP mocks behaviour isn't the same. `expects()` works only to restrict HTTP calls inside a web server, but not for tests.

What do you think about automatic addition of assertions for HTTP mocks, like it's done for class/interface mocks?

**Comment by lstrojny** [comment]
Can you show me an example?

**Comment by alexeyshockov** [comment]
Example: when I use `once()` for a HTTP mock, I expect that my test will fail if the mock don't be called.

So I expect a test below to be failed:
```php
    public function itShouldFail()
    {
        $this->http->mock
            ->once()
            ->when()
                ->methodIs('GET')
                ->pathIs('/test')
            ->then()
                ->body('Test.')
            ->end();

        assertTrue(true);
    }
```

**Comment by lstrojny** [comment]
It’s true that the term mock is ill-used here. It’s more of an HTTP stub/fake library. I don’t want to change the semantics of `once()` and `exactly()` but maybe there is another way to introduce mocking.

**Comment by alexeyshockov** [comment]
Agree. Maybe it's better to release 1.0 version with current API (because it's mature already) and prepare changes for the second version? I think that it makes no sense to freeze current terms forever and develop all new things on top of them.

We can build two services: `mock` and `stub`. API will be almost the same, semantics will be slightly different. But it will be clear by names.

What do you think?

**Comment by franzliedke** [comment]
I think setting up stubs with the current API works well. Turning them into mocks (kinda) is easily possible by making assertions against the `$this->http->requests` object using [the Recording API](https://github.com/InterNations/http-mock/blob/master/doc/recording.md) after the fact.

**Comment by lstrojny** [comment]
Closing this after a long time of inactivity 😄
