### ISSUE TITLE
PHP 5.6 as minimum required version

### ISSUE THREAD

**Issue by alexeyshockov** [InterNations/http-mock#29]
`symfony/process` already requires PHP 5.5.9, the whole library will not work with PHP < 5.5.9.

So the current requirement (5.4.0) is a lie :)

**Comment by lstrojny** [comment]
Thank you!

**Comment by chrisjohnson00** [comment]
5.5.9 is the latest version for Ubuntu 14.x, forcing to >=5.6 breaks "simple support" on ubuntu 14.  Would this also work on >=5.5.9?
