### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by JiankangMai** [InterNations/http-mock#37]
`Failed to listen on 127.0.0.1:33371 (reason: Address already in use)` appear second Test unit class which in the same life cycle.
it seems that it have no release socket In teardown() really or Http-mock is not a singleInstance.

**Comment by JiankangMai** [comment]
Sorry,I found the invoke of Symfony\Component\Process->stop() in HttpMockTrait::tearDownHttpMockAfterClass()
https://github.com/Codeception/Codeception/issues/3198
Oh,it's a “feature” of codeception framwork,not http-mock.

**Comment by lstrojny** [comment]
@JiankangMai alternatively you can indeed do set up and tear down in the per test steps, not in the per class steps. That’s less efficient as it needs to restart the server more often but should work.
