### ISSUE TITLE
PHPUnit WebTestCase failing when 2 tests are using the same port.

### ISSUE THREAD

**Issue by Locustv2** [InterNations/http-mock#38]
Using PHP 5.6.18 with PHPUnit 5.7.5, the following error is produced:
`UnexpectedValueException: Expected status code 200 from "/_request/2", got 404`

The call is from the first test with a loop which is calling `$this->http->requests->at($i);`.

The codes in the first class is:

```php
/**
     * @beforeClass
     * @SuppressWarnings(PHPMD.StaticAccess)
     */
    public static function init()
    {
        static::setUpHttpMockBeforeClass('8880', 'localhost');
    }

    /**
     * @afterClass
     */
    public static function shutdown()
    {
        static::tearDownHttpMockAfterClass();
    }

    public function testMethod()
    {
        // do stuffs
           $this->http->requests->at($i);
        //do other stuffs
    }
```

And the second class is

```php
    public static function setUpBeforeClass()
    {
        static::setUpHttpMockBeforeClass('8880', 'localhost');
    }

    public static function tearDownAfterClass()
    {
        static::tearDownHttpMockAfterClass();
    }

    // other stuff
```

Both class extends from `WebTestCase` and use the `HttpMockTrait`

When the port is different in the second class or the second test is skipped, the test runs successfully.

**Comment by lstrojny** [comment]
In your first testcase, can you modify `tearDownAfterClass()` and add `var_dump(`ps ax | grep php`);` after the `static::tearDownHttpMockAfterClass()`?

**Comment by Locustv2** [comment]
For some reasons, when i added the `var_dump(`ps ax | grep php`);` it did not fail. I removed it and it still did not fail. 

FYI: besides changing ports and setting back the same port on both test case, nothing has been changed.

**Comment by ademarco** [comment]
On #41 tests are green again, it was about choosing fixing composer on the right version of PHPUnit, we could maybe close this issue? \cc @lstrojny

**Comment by lstrojny** [comment]
Closing
