### ISSUE TITLE
register different successive responses for the same endpoint

### ISSUE THREAD

**Issue by gturri** [InterNations/http-mock#61]
Hi,

first of all, thanks for this software.

Then, here is a feature request:
I'm trying to test a "retry" feature in my http client. So I would like to be able to set up http-mock so that the 1st query it receives returns a response with status code 500, and so that the 2nd query it receives returns a response with status code 200.
I've looked at the doc, made some experiments but couldn't find a way to do i (in particular I tried to redefine the behavior of the mock in a `->then()->callback(...)` but that didn't seem to work).

To put it in a nutshell:

- Is it already possible to do this kind of setup? If yes, would it be possible to add some doc about it?
- If it's not possible, does it seem like a feature you might want to consider?

**Comment by lstrojny** [comment]
I don’t think we are exposing any functionality like that yet but everything should be in place to relatively easily expose it. Here is a patch to outline the idea:
```diff
diff --git a/src/MockBuilder.php b/src/MockBuilder.php
index b79fc8f..35b9a6d 100644
--- a/src/MockBuilder.php
+++ b/src/MockBuilder.php
@@ -50,6 +50,28 @@ class MockBuilder
         return $this;
     }
 
+    public function first()
+    {
+        $this->nth(0);
+    }
+
+    public function second()
+    {
+        $this->nth(1);
+    }
+
+    public function third()
+    {
+        $this->nth(2);
+    }
+
+    public function nth($position)
+    {
+        $this->limiter = static function ($runs) use ($position) {
+            return $runs === $position;
+        };
+    }
+
     public function any()
     {
         $this->limiter = static function () {
```


Happy to get a PR for that with tests and docs, looks like a sensible feature. Interested in carrying this forward?

**Comment by gturri** [comment]
Thanks for replying so quickly!
I'll try to give a try. Sure, if I manage to have something that works
fine, I would be thrilled to try to take the time to do a proper PR!

Le jeu. 6 mai 2021 à 13:13, Lars Strojny ***@***.***> a
écrit :

**Comment by gturri** [comment]
Thanks to your pointers I managed to do this PR #62 . Let me know if it's ok with you or not.

**Comment by gturri** [comment]
Thanks for your work on #64 !

Do you know when you may release a new version which would include this feature?

**Comment by gturri** [comment]
(I'm seeing that I forgot to close this issue though it is fixed, I'm doing it now)
